2020-12-03T10:46:28.1130317+07:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2020-12-03T10:46:28.1259334+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2020-12-03T10:46:28.1292604+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-12-03T10:46:28.1365122+07:00  [INF] Hosting environment: "Development" (c3307c92)
2020-12-03T10:46:28.1419099+07:00  [INF] Content root path: "E:\KLTN\WebsiteLaptop\WebsiteLaptop.Application" (b5d60022)
2020-12-03T10:46:44.6490795+07:00 0HM4N7O1USB9D:00000009 [INF] User logged in. (fdce0db4)
2020-12-03T10:47:25.2654392+07:00 0HM4N7O1USB9D:0000001F [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.NullReferenceException: Object reference not set to an instance of an object.
   at WebsiteLaptop.Service.Implementation.RoleService.GetAllAsync() in E:\KLTN\WebsiteLaptop\WebsiteLaptop.Service\Implementation\RoleService.cs:line 68
   at WebsiteLaptop.Application.Areas.Admin.Controllers.RoleController.GetAll() in E:\KLTN\WebsiteLaptop\WebsiteLaptop.Application\Areas\Admin\Controllers\RoleController.cs:line 25
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-12-03T10:55:35.2708666+07:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2020-12-03T10:55:35.2788516+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2020-12-03T10:55:35.2808426+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-12-03T10:55:35.2834213+07:00  [INF] Hosting environment: "Development" (c3307c92)
2020-12-03T10:55:35.2849252+07:00  [INF] Content root path: "E:\KLTN\WebsiteLaptop\WebsiteLaptop.Application" (b5d60022)
2020-12-03T10:55:54.2115012+07:00 0HM4N7T528IUJ:0000000B [INF] User logged in. (fdce0db4)
2020-12-03T11:13:13.0754256+07:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2020-12-03T11:13:13.0878054+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2020-12-03T11:13:13.0906808+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-12-03T11:13:13.0997627+07:00  [INF] Hosting environment: "Development" (c3307c92)
2020-12-03T11:13:13.1030541+07:00  [INF] Content root path: "E:\KLTN\WebsiteLaptop\WebsiteLaptop.Application" (b5d60022)
2020-12-03T11:13:44.9468238+07:00 0HM4N8708OP38:00000001 [INF] User logged in. (fdce0db4)
2020-12-03T11:15:09.3406555+07:00 0HM4N8708OP39:0000000F [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.NullReferenceException: Object reference not set to an instance of an object.
   at WebsiteLaptop.Service.Implementation.RoleService.GetAllAsync() in E:\KLTN\WebsiteLaptop\WebsiteLaptop.Service\Implementation\RoleService.cs:line 68
   at WebsiteLaptop.Application.Areas.Admin.Controllers.RoleController.GetAll() in E:\KLTN\WebsiteLaptop\WebsiteLaptop.Application\Areas\Admin\Controllers\RoleController.cs:line 27
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-12-03T11:15:16.7071863+07:00 0HM4N8708OP39:00000011 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.NullReferenceException: Object reference not set to an instance of an object.
   at WebsiteLaptop.Service.Implementation.RoleService.GetAllAsync() in E:\KLTN\WebsiteLaptop\WebsiteLaptop.Service\Implementation\RoleService.cs:line 68
   at WebsiteLaptop.Application.Areas.Admin.Controllers.RoleController.GetAll() in E:\KLTN\WebsiteLaptop\WebsiteLaptop.Application\Areas\Admin\Controllers\RoleController.cs:line 27
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-12-03T11:15:41.5899300+07:00 0HM4N8708OP3A:00000003 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.NullReferenceException: Object reference not set to an instance of an object.
   at WebsiteLaptop.Service.Implementation.RoleService.GetAllAsync() in E:\KLTN\WebsiteLaptop\WebsiteLaptop.Service\Implementation\RoleService.cs:line 68
   at WebsiteLaptop.Application.Areas.Admin.Controllers.RoleController.GetAll() in E:\KLTN\WebsiteLaptop\WebsiteLaptop.Application\Areas\Admin\Controllers\RoleController.cs:line 27
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-12-03T11:20:59.3902924+07:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2020-12-03T11:20:59.3985101+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2020-12-03T11:20:59.4011352+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-12-03T11:20:59.4027354+07:00  [INF] Hosting environment: "Development" (c3307c92)
2020-12-03T11:20:59.4047166+07:00  [INF] Content root path: "E:\KLTN\WebsiteLaptop\WebsiteLaptop.Application" (b5d60022)
2020-12-03T11:21:17.7948955+07:00 0HM4N8BB713FE:00000005 [INF] User logged in. (fdce0db4)
2020-12-03T11:22:34.7638323+07:00 0HM4N8BB713FF:00000033 [INF] User logged in. (fdce0db4)
2020-12-03T11:22:51.5775230+07:00 0HM4N8BB713FF:0000003D [INF] User logged in. (fdce0db4)
2020-12-03T11:34:32.3511697+07:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2020-12-03T11:34:32.3640276+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2020-12-03T11:34:32.3694599+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-12-03T11:34:32.3732686+07:00  [INF] Hosting environment: "Development" (c3307c92)
2020-12-03T11:34:32.3765623+07:00  [INF] Content root path: "E:\KLTN\WebsiteLaptop\WebsiteLaptop.Application" (b5d60022)
2020-12-03T11:34:41.1630736+07:00 0HM4N8ITGMLP7:0000000B [INF] User logged in. (fdce0db4)
2020-12-03T11:35:41.2276180+07:00  [INF] Application is shutting down... (90f52c38)
2020-12-03T14:11:53.1550711+07:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2020-12-03T14:11:53.1650046+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2020-12-03T14:11:53.1705996+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-12-03T14:11:53.1780177+07:00  [INF] Hosting environment: "Development" (c3307c92)
2020-12-03T14:11:53.1845211+07:00  [INF] Content root path: "E:\KLTN\WebsiteLaptop\WebsiteLaptop.Application" (b5d60022)
2020-12-03T14:12:05.2693575+07:00 0HM4NBAR5JELO:00000033 [INF] User logged in. (fdce0db4)
2020-12-03T14:12:17.1706897+07:00 0HM4NBAR5JELO:00000055 [ERR] The view '"Index"' was not found. Searched locations: ["/Areas/Admin/Views/Function/Index.en-US.cshtml", "/Areas/Admin/Views/Function/Index.en.cshtml", "/Areas/Admin/Views/Function/Index.cshtml", "/Areas/Admin/Views/Shared/Index.en-US.cshtml", "/Areas/Admin/Views/Shared/Index.en.cshtml", "/Areas/Admin/Views/Shared/Index.cshtml", "/Views/Shared/Index.en-US.cshtml", "/Views/Shared/Index.en.cshtml", "/Views/Shared/Index.cshtml", "/Pages/Shared/Index.en-US.cshtml", "/Pages/Shared/Index.en.cshtml", "/Pages/Shared/Index.cshtml"] (9bb2756c)
2020-12-03T14:12:17.2504836+07:00 0HM4NBAR5JELO:00000055 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: The view 'Index' was not found. The following locations were searched:
/Areas/Admin/Views/Function/Index.en-US.cshtml
/Areas/Admin/Views/Function/Index.en.cshtml
/Areas/Admin/Views/Function/Index.cshtml
/Areas/Admin/Views/Shared/Index.en-US.cshtml
/Areas/Admin/Views/Shared/Index.en.cshtml
/Areas/Admin/Views/Shared/Index.cshtml
/Views/Shared/Index.en-US.cshtml
/Views/Shared/Index.en.cshtml
/Views/Shared/Index.cshtml
/Pages/Shared/Index.en-US.cshtml
/Pages/Shared/Index.en.cshtml
/Pages/Shared/Index.cshtml
   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-12-03T14:15:09.2331493+07:00 0HM4NBAR5JELO:0000008D [INF] User logged in. (fdce0db4)
2020-12-03T14:37:29.9402788+07:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2020-12-03T14:37:29.9483688+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2020-12-03T14:37:29.9519211+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-12-03T14:37:29.9545577+07:00  [INF] Hosting environment: "Development" (c3307c92)
2020-12-03T14:37:29.9590913+07:00  [INF] Content root path: "E:\KLTN\WebsiteLaptop\WebsiteLaptop.Application" (b5d60022)
2020-12-03T14:38:22.5098543+07:00 0HM4NBP55TKD6:0000000B [INF] User logged in. (fdce0db4)
2020-12-03T14:38:39.8984987+07:00 0HM4NBP55TKD6:00000015 [INF] User logged in. (fdce0db4)
2020-12-03T14:39:01.7600412+07:00 0HM4NBP55TKD6:00000035 [INF] User logged in. (fdce0db4)
2020-12-03T14:41:47.9402094+07:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2020-12-03T14:41:47.9472802+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2020-12-03T14:41:47.9497022+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-12-03T14:41:47.9524469+07:00  [INF] Hosting environment: "Development" (c3307c92)
2020-12-03T14:41:47.9556507+07:00  [INF] Content root path: "E:\KLTN\WebsiteLaptop\WebsiteLaptop.Application" (b5d60022)
2020-12-03T14:41:58.0408719+07:00 0HM4NBRHVHV9U:0000000B [INF] User logged in. (fdce0db4)
2020-12-03T14:42:14.6347113+07:00 0HM4NBRHVHV9U:00000025 [INF] User logged in. (fdce0db4)
2020-12-03T14:44:04.1241793+07:00 0HM4NBRHVHV9U:00000047 [INF] User logged in. (fdce0db4)
2020-12-03T23:36:18.8044954+07:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2020-12-03T23:36:18.8112857+07:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2020-12-03T23:36:18.8173942+07:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-12-03T23:36:18.8200573+07:00  [INF] Hosting environment: "Development" (c3307c92)
2020-12-03T23:36:18.8225314+07:00  [INF] Content root path: "E:\Code KLTN\WebsiteLaptop\WebsiteLaptop.Application" (b5d60022)
2020-12-03T23:37:01.0485038+07:00 0HM4NL67S8QSA:00000001 [INF] User logged in. (fdce0db4)
